// Mapeamento de Estados para Siglas
export const ESTADOS_MAP: Record<string, string> = {
  'Acre': 'AC',
  'Alagoas': 'AL',
  'Amapá': 'AP',
  'Amazonas': 'AM',
  'Bahia': 'BA',
  'Ceará': 'CE',
  'Distrito Federal': 'DF',
  'Espírito Santo': 'ES',
  'Goiás': 'GO',
  'Maranhão': 'MA',
  'Mato Grosso': 'MT',
  'Mato Grosso do Sul': 'MS',
  'Minas Gerais': 'MG',
  'Pará': 'PA',
  'Paraíba': 'PB',
  'Paraná': 'PR',
  'Pernambuco': 'PE',
  'Piauí': 'PI',
  'Rio de Janeiro': 'RJ',
  'Rio Grande do Norte': 'RN',
  'Rio Grande do Sul': 'RS',
  'Rondônia': 'RO',
  'Roraima': 'RR',
  'Santa Catarina': 'SC',
  'São Paulo': 'SP',
  'Sergipe': 'SE',
  'Tocantins': 'TO'
}

// Lista mockada de Cidades Principais para o Filtro
export const CIDADES_MOCK = [
  'Rio Branco - AC',
  'Maceió - AL',
  'Macapá - AP',
  'Manaus - AM',
  'Manacapuru - AM',
  'Salvador - BA',
  'Fortaleza - CE',
  'Jaguaribara - CE',
  'Brasília - DF',
  'Vitória - ES',
  'Goiânia - GO',
  'São Luís - MA',
  'Cuiabá - MT',
  'Campo Grande - MS',
  'Belo Horizonte - MG',
  'Lagoa da Prata - MG',
  'Belém - PA',
  'João Pessoa - PB',
  'Curitiba - PR',
  'Recife - PE',
  'Caruaru - PE',
  'Petrolina - PE',
  'Olinda - PE',
  'Teresina - PI',
  'Rio de Janeiro - RJ',
  'Niterói - RJ',
  'Natal - RN',
  'Porto Alegre - RS',
  'Porto Velho - RO',
  'Boa Vista - RR',
  'Florianópolis - SC',
  'Blumenau - SC',
  'São Paulo - SP',
  'Taubaté - SP',
  'Campinas - SP',
  'Aracaju - SE',
  'Palmas - TO'
]
